baseURL: https://antoniohnz.me/

languageCode: es-ES
title: "Tony"

module:
  imports:
    - path: github.com/hugo-toha/toha/v4
  mounts:
    - source: static/files
      target: static/files
    - source: ./node_modules/flag-icon-css/flags
      target: static/flags
    - source: ./node_modules/@fontsource/mulish/files
      target: static/files
    - source: ./node_modules/katex/dist/fonts
      target: static/fonts

defaultContentLanguage: es

languages:
  es:
    languageName: Español
    weight: 1

  en:
    languageName: English
    weight: 2

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON
  page:
  - HTML
  - RSS

enableEmoji: true

# Site parameters
params:
  background: images/site/city-background.jpg
  image_404: images/site/image_404.png

  logo:
    main: images/logos/main-logo.png
    inverted: images/logos/inverted-logo.png
    favicon: images/logos/favicon.png

  features:
    # Provide newsletter configuration. This feature hasn't been implemented yet.
    # Currently, you can just hide it from the footer.
    newsletter:
      enable: false

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    tags:
      enable: true

    analytics:
      enabled: true
      services:
        counterDev:
          id: 5e29af01-31e1-4003-be2f-d38966ecf4fb
          referrerPolicy: no-referrer-when-downgrade

    darkMode:
      enable: true

    portfolio:
      enable: false

    blog:
      enable: false
      shareButtons:
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true