baseURL: https://antoniohnz.me/

languageCode: es-ES
title: "Tony"
theme: "toha"

defaultContentLanguage: es

languages:
  es:
    languageName: Español
    weight: 1

  en:
    languageName: English
    weight: 2

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON
  page:
  - HTML
  - RSS

enableEmoji: true

# Site parameters
params:
  background: images/site/city-background.jpg
  image_404: images/site/image_404.png

  logo:
    main: images/logos/main-logo.png
    inverted: images/logos/inverted-logo.png
    favicon: images/logos/favicon.png


  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  enableTags: true

  features:
    analytics:
      enabled: true
      counterDev:
        id: toniop99
        referrerPolicy: no-referrer-when-downgrade

    portfolio:
      enable: false

    blog:
      enable: false
      shareButtons:
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true